version: '3.6'
services:
  proxy:
    image: traefik:alpine
    container_name: traefik
    labels:
      - traefik.backend=monitor
      - traefik.frontend.rule=Host:monitor.local
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/certs:/certs
    ports:
       - 80:80
       - 443:443
       - 8080:8080
  customers:
    build: ./customers
    image: my-project/customers
    container_name: customers
    labels:
      - traefik.backend=customers
      - traefik.frontend.rule=Host:customers.local
      - traefik.enable=true

  products:
    build: ./products
    image: my-project/products
    container_name: products
    labels:
      - traefik.backend=products
      - traefik.frontend.rule=Host:products.local
      - traefik.enable=true
  
  shops:
    build: ./shops
    image: my-project/shops
    container_name: shops
    labels:
      - traefik.backend=shops
      - traefik.frontend.rule=Host:shops.local
      - traefik.enable=true

  addresses:
    build: ./addresses
    image: my-project/addresses
    container_name: addresses
    labels:
      - traefik.backend=addresses
      - traefik.frontend.rule=Host:addresses.local
      - traefik.enable=true

  db:
    image: mongo:3.3
    container_name: mongodb
    ports:
      - target: 27018
        published: 27018
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./backup
        target: /backup
